vic = User.create(name: 'Vic', email: 'lam.vic.k@gmail.com', password: '1', password_confirmation: '1')
dave = User.create(name: 'Dave', email: 'davidkorff@gmail.com', password: '1', password_confirmation: '1')
liz = User.create(name: 'Liz', email: 'elizabethjjacobs@gmail.com', password: '1', password_confirmation: '1')

poll1 = Poll.create(title: 'Puppy or Rainbow', user_id: '1')
poll2 = Poll.create(title: 'Cat rolled in paper or Brocolli Treehouse...you decide!', user_id: '2')
poll3 = Poll.create(title: 'This or That', user_id: '2')
poll4 = Poll.create(title: 'Mask vs Rugrats', user_id: '3')
poll5 = Poll.create(title: 'The Ring...or Scream?', user_id: '3')

poll1_1 = PollOption.create(text: 'Pups', poll_id: '1', image: "https://s-media-cache-ak0.pinimg.com/236x/63/43/9b/63439b05d58531785d61655c99907d10.jpg")
poll1_2 = PollOption.create(text: 'Rainbow', poll_id: '1', image: "https://media.mnn.com/assets/images/2016/07/Rainbow-Stretching-Hilly-Forest-Mountains.jpg.638x0_q80_crop-smart.jpg")
poll2_1 = PollOption.create(text: 'Cat', poll_id: '2', image: "https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg")
poll2_2 = PollOption.create(text: 'Brocolli', poll_id: '2', image: "http://cdn.playbuzz.com/cdn/38402fff-32a3-4e78-a532-41f3a54d04b9/cc513a85-8765-48a5-8481-98740cc6ccdc.jpg")
poll3_1 = PollOption.create(text: 'This', poll_id: '3', image: "https://pbs.twimg.com/profile_images/468074714368200704/lg6ZrVv8.jpeg")
poll3_2 = PollOption.create(text: 'That', poll_id: '3', image: "http://68.media.tumblr.com/13a80eb9033c42bde84165c17cda1548/tumblr_ohtitri5rY1skf02io6_500.png")
poll4_1 = PollOption.create(text: 'Weird Mask', poll_id: '4', image: "http://www.crayola.com/~/media/Art%20Technique%20Imgs/Model%20Magic/Model_Magic_Mask.jpg")
poll4_2 = PollOption.create(text: 'Rugrat', poll_id: '4', image: "http://vignette3.wikia.nocookie.net/rugrats/images/a/ad/Chuckie_Finster.png/revision/latest?cb=20130515181817")
poll5_1 = PollOption.create(text: 'Japanese Horror', poll_id: '5', image: "http://cdn.collider.com/wp-content/uploads/2015/09/the-ring-samara.png")
poll5_2 = PollOption.create(text: 'American Slasher', poll_id: '5', image: "http://static.rogerebert.com/uploads/movie/movie_poster/scream-1996/large_ewi7gYW22t8T3piRvrXO73GlzuL.jpg")

vote1_p1 = Vote.create(poll_option_id: '1', user_id: '1')
vote2_p1 = Vote.create(poll_option_id: '2', user_id: '2')
vote3_p1 = Vote.create(poll_option_id: '2', user_id: '3')
