vic = User.create(name: 'Vic', email: 'lam.vic.k@gmail.com', password: '1', password_confirmation: '1')
dave = User.create(name: 'Dave', email: 'davidkorff@gmail.com', password: '1', password_confirmation: '1')
liz = User.create(name: 'Liz', email: 'elizabethjjacobs@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user4', email: 'user4@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user5', email: 'user5@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user6', email: 'user6@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user7', email: 'user7@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user8', email: 'user8@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user9', email: 'user9@gmail.com', password: '1', password_confirmation: '1')
User.create(name: 'user10', email: 'user10@gmail.com', password: '1', password_confirmation: '1')


poll1 = Poll.create(title: 'Puppy or Rainbow', user_id: '1')
poll2 = Poll.create(title: 'Cat rolled in paper or Brocolli Treehouse...you decide!', user_id: '2')
poll3 = Poll.create(title: 'This or That', user_id: '2')
poll4 = Poll.create(title: 'Mask vs Rugrats', user_id: '2')
poll5 = Poll.create(title: 'The Ring...or Scream?', user_id: '2')
Poll.create(title: 'Which is Better?', user_id: '2')
Poll.create(title: 'Which is the better car?', user_id: '2')
Poll.create(title: 'Favorite City?', user_id: '2')
Poll.create(title: 'Cuter Dog', user_id: '1')
Poll.create(title: 'Better Computer', user_id: '1')
Poll.create(title: 'Better coding Bootcamp', user_id: '1')
Poll.create(title: 'Tastier Food', user_id: '3')
Poll.create(title: 'Better coordinate system', user_id: '2')
Poll.create(title: 'Favorite particle attribute', user_id: '1')
Poll.create(title: 'Better coding language', user_id: '3')
Poll.create(title: 'How to rule a principality', user_id: '1')
Poll.create(title: 'Which road to take?', user_id: '1')
Poll.create(title: 'which weighs more?', user_id: '2')
Poll.create(title: 'Who will win?', user_id: '2')
Poll.create(title: 'Which reins supreme!?', user_id: '1')
Poll.create(title: 'Better name', user_id: '3')
Poll.create(title: "What is the best name for a kitty?", user_id: '3')
Poll.create(title: "Where to go on my honeymoon?", user_id: '3')
Poll.create(title: "Wine or beer?", user_id: '2')
Poll.create(title: "sexiest nerd", user_id: '2')


poll1_1 = PollOption.create(text: 'Pups', poll_id: '1', image: "https://s-media-cache-ak0.pinimg.com/236x/63/43/9b/63439b05d58531785d61655c99907d10.jpg")
poll1_2 = PollOption.create(text: 'Rainbow', poll_id: '1', image: "https://media.mnn.com/assets/images/2016/07/Rainbow-Stretching-Hilly-Forest-Mountains.jpg.638x0_q80_crop-smart.jpg")
poll2_1 = PollOption.create(text: 'Cat', poll_id: '2', image: "https://i.ytimg.com/vi/tntOCGkgt98/maxresdefault.jpg")
poll2_2 = PollOption.create(text: 'Brocolli', poll_id: '2', image: "http://cdn.playbuzz.com/cdn/38402fff-32a3-4e78-a532-41f3a54d04b9/cc513a85-8765-48a5-8481-98740cc6ccdc.jpg")
poll3_1 = PollOption.create(text: 'This', poll_id: '3', image: "https://pbs.twimg.com/profile_images/468074714368200704/lg6ZrVv8.jpeg")
poll3_2 = PollOption.create(text: 'That', poll_id: '3', image: "http://68.media.tumblr.com/13a80eb9033c42bde84165c17cda1548/tumblr_ohtitri5rY1skf02io6_500.png")
poll4_1 = PollOption.create(text: 'Weird Mask', poll_id: '4', image: "http://www.crayola.com/~/media/Art%20Technique%20Imgs/Model%20Magic/Model_Magic_Mask.jpg")
poll4_2 = PollOption.create(text: 'Rugrat', poll_id: '4', image: "http://vignette3.wikia.nocookie.net/rugrats/images/a/ad/Chuckie_Finster.png/revision/latest?cb=20130515181817")
poll5_1 = PollOption.create(text: 'Japanese Horror', poll_id: '5', image: "http://cdn.collider.com/wp-content/uploads/2015/09/the-ring-samara.png")
poll5_2 = PollOption.create(text: 'American Slasher', poll_id: '5', image: "http://static.rogerebert.com/uploads/movie/movie_poster/scream-1996/large_ewi7gYW22t8T3piRvrXO73GlzuL.jpg")
PollOption.create(text: 'Twitter', poll_id: '6', image: "https://lh3.ggpht.com/lSLM0xhCA1RZOwaQcjhlwmsvaIQYaP3c5qbDKCgLALhydrgExnaSKZdGa8S3YtRuVA=w300")
PollOption.create(text: 'FaceBook', poll_id: '6', image: "https://www.facebook.com/images/fb_icon_325x325.png")
PollOption.create(text: 'Lamborghini', poll_id: '7', image: "https://www.lamborghini.com/en-en/sites/en-en/files/DAM/it/models_gateway/blocks/special.png")
PollOption.create(text: 'Ferrari', poll_id: '7', image: "http://buyersguide.caranddriver.com/media/assets/submodel/6873.jpg")
PollOption.create(text: 'New York', poll_id: '8', image: "http://www.newyorker.com/wp-content/uploads/2015/12/Veix-Goodbye-New-York-Color-1200.jpg")
PollOption.create(text: 'Los Angeles', poll_id: '8', image: "http://cdn-media.backstage.com/files/media/uploads/zinnia/2016/07/26/shutterstock_186048416.jpg.644x671_q100.jpg")
PollOption.create(text: 'This fluff ball', poll_id: '9', image: "https://i.ytimg.com/vi/opKg3fyqWt4/hqdefault.jpg")
PollOption.create(text: 'this fluff ball', poll_id: '9', image: "http://iheartdogs.com/wp-content/uploads/2015/01/Screenshot-2015-01-17-16.15.29.png")
PollOption.create(text: 'Mac', poll_id: '10', image: "https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2013/11/mac_desktops_apple_art.jpg?itok=LR2345AE")
PollOption.create(text: 'PC', poll_id: '10', image: "https://i.ytimg.com/vi/5kopNTvReGU/maxresdefault.jpg")
PollOption.create(text: 'App Academy', poll_id: '11', image: "https://p5.zdassets.com/hc/settings_assets/949671/200252358/ytySguzPxy92CMwTwD4fxg-logo-emblem-red.png")
PollOption.create(text: 'General Assembly', poll_id: '11', image: "https://pbs.twimg.com/profile_images/813584000082214912/5U3iZVs-.jpg")
PollOption.create(text: 'Pizza', poll_id: '12', image: "http://www.cicis.com/media/1138/pizza_trad_pepperoni.png")
PollOption.create(text: 'Ice Cream', poll_id: '12', image: "http://impossiblehouse.com/wp-content/uploads/2016/12/ice-cream-maker-12.jpg")
PollOption.create(text: 'Polar', poll_id: '13', image: "http://mathworld.wolfram.com/images/eps-gif/PolarCoordinatesGraphPaper_1000.gif")
PollOption.create(text: 'Cartesian', poll_id: '13', image: "http://fmslogo.sourceforge.net/workshop/img/cartesian-coordinate-system.png")
PollOption.create(text: 'Momentum', poll_id: '14', image: "https://www.indoorcomfortmarketing.com/wp-content/uploads/2013/02/web-delta-p-for-carey-300x170.jpg")
PollOption.create(text: 'Poistion', poll_id: '14', image: "http://blogs.wit.edu/accelerate/files/2013/08/Delta-X-Logo-rev-1-1-1024x1024.png")
PollOption.create(text: 'Ruby', poll_id: '15', image: "https://rebornix.gallerycdn.vsassets.io/extensions/rebornix/ruby/0.10.4/1480705685716/Microsoft.VisualStudio.Services.Icons.Default")
PollOption.create(text: 'JavaScript', poll_id: '15', image: "http://www.javatpoint.com/images/javascript/javascript_logo.png")
PollOption.create(text: 'Through Love', poll_id: '16', image: "https://assets.ec.quoracdn.net/main-thumb-t-1800-200-lOn8kKfhqfcTcKdt2GwaLfGnC0jEjHmV.jpeg")
PollOption.create(text: 'Through FEAR', poll_id: '16', image: "http://reallifeglobal.com/wp-content/uploads/2014/10/FEAR.jpg?467a33")
PollOption.create(text: 'The one less traveled', poll_id: '17', image: "https://jeparleamericain.files.wordpress.com/2011/11/the_road_not_taken_by_anachronist84.jpg")
PollOption.create(text: 'The one with the bear', poll_id: '17', image: "http://runtrails.net/2012/images/Alaska/june29_6.jpg")
PollOption.create(text: 'Pound of feathers', poll_id: '18', image: "https://domesticintelligence.files.wordpress.com/2010/12/2-weights2.jpg")
PollOption.create(text: 'My fathers approval', poll_id: '18', image: "http://www.telegraph.co.uk/content/dam/wellbeing/2016/09/30/Paxman00217218_Jeremy_Paxman__EUROPE_THE_FINAL_DEBATE_WITH_JEREMY_PAXMAN_Channel_4_wk25_handout__Cha-large_trans++qVzuuqpFlyLIwiB6NTmJwfSVWeZ_vEN7c6bHu2jJnT8.jpg")
PollOption.create(text: 'Black Jack', poll_id: '19', image: "https://i.ytimg.com/vi/-9YGKFdP6sY/hqdefault.jpg")
PollOption.create(text: 'Jack Black', poll_id: '19', image: "https://www.biography.com/.image/c_fill,cs_srgb,dpr_1.0,g_face,h_300,q_80,w_300/MTE5NDg0MDU1MjIwNjg0MzAz/jack-black-9542484-1-402.jpg")
PollOption.create(text: 'Unstoppable Force', poll_id: '20', image: "http://a.espncdn.com/combiner/i?img=/i/teamlogos/nfl/500/ne.png&h=150&w=150")
PollOption.create(text: 'Immovable Object', poll_id: '20', image: "http://www.towntalk.co.uk/subdomains/lib/image.php/27007_immovable-roadblock-closes-kendray-street.jpg?image=http://www.barnsley.towntalk.co.uk/images_folder/newsimg/27007_immovable-roadblock-closes-kendray-street.jpg&domain=.co.uk")
PollOption.create(text: 'Orca', poll_id: '21', image: "http://www.defenders.org/sites/default/files/magaizine-spring-2016-orca-dave-ellifrit-center-for-whale-research-nmfs-permit-15569-dfo-sara-272_.jpg")
PollOption.create(text: 'SeaPanda', poll_id: '21', image: "http://mediacdn.snorgcontent.com/media/catalog/product/cache/1/image/1800x/6b9ffbf72458f4fd2d3cb995d92e8889/s/e/sea-panda-newthumb.png")
PollOption.create(text: "Elaine (aka Lainey)", poll_id: '22', image: "http://cdn1-www.cattime.com/assets/uploads/gallery/persian-cats-and-kittens/persian-cats-and-kittens-8.jpg")
PollOption.create(text: "Mooskers", poll_id: '22', image: "http://www.catbreedslist.com/uploads/allimg/cat-pictures/British-Shorthair-1.jpg")
PollOption.create(text: "Peru", poll_id: '23', image: "http://www.machupicchu.org/img/top/top-destinations-machu-picchu-1.jpg")
PollOption.create(text: "Italy Ooh La La", poll_id: '23', image: "http://fullwonders.com/wp-content/uploads/2016/10/portofino-italia.jpg")
PollOption.create(text: "Wine", poll_id: '24', image: "http://punchdrink.com/wp-content/uploads/2016/03/Article-Second-Cheapest-Wine-By-the-Glass-Restaurant-Dining-NYC-Gramercy-Tavern-Juliette-Pope-David-Lynch-Jose-Andres.jpg")
PollOption.create(text: "Beer", poll_id: '24', image: "https://rks-inside-prod.s3-us-west-1.amazonaws.com/lists/avatars/000/000/047/original_o-PINT-GLASS-BEER-facebook.jpg?1473216955")
PollOption.create(text: "Bill gates", poll_id: '25', image: "http://ncmedia.azureedge.net/ncmedia/2014/09/billg1_print.jpg")
PollOption.create(text: "elon musk", poll_id: '25', image: "http://az616578.vo.msecnd.net/files/2016/07/02/636030757259556361-1129479309_elon-musk.jpg")


vote1_p1 = Vote.create(poll_option_id: '1', user_id: '1')
vote2_p1 = Vote.create(poll_option_id: '2', user_id: '2')
vote3_p1 = Vote.create(poll_option_id: '2', user_id: '3')
Vote.create(poll_option_id: '3', user_id: '4')
Vote.create(poll_option_id: '3', user_id: '5')
Vote.create(poll_option_id: '3', user_id: '6')
Vote.create(poll_option_id: '4', user_id: '7')

Vote.create(poll_option_id: '5', user_id: '8')
Vote.create(poll_option_id: '5', user_id: '9')
Vote.create(poll_option_id: '5', user_id: '10')
Vote.create(poll_option_id: '5', user_id: '1')
Vote.create(poll_option_id: '5', user_id: '2')
Vote.create(poll_option_id: '5', user_id: '3')
Vote.create(poll_option_id: '5', user_id: '4')
Vote.create(poll_option_id: '6', user_id: '5')
Vote.create(poll_option_id: '6', user_id: '6')

Vote.create(poll_option_id: '7', user_id: '7')
Vote.create(poll_option_id: '7', user_id: '8')

Vote.create(poll_option_id: '10', user_id: '9')

Vote.create(poll_option_id: '11', user_id: '10')
Vote.create(poll_option_id: '11', user_id: '1')
Vote.create(poll_option_id: '12', user_id: '2')
Vote.create(poll_option_id: '12', user_id: '3')
Vote.create(poll_option_id: '12', user_id: '4')
Vote.create(poll_option_id: '12', user_id: '5')
Vote.create(poll_option_id: '12', user_id: '6')
Vote.create(poll_option_id: '12', user_id: '7')
Vote.create(poll_option_id: '12', user_id: '8')

Vote.create(poll_option_id: '13', user_id: '9')
Vote.create(poll_option_id: '13', user_id: '10')
Vote.create(poll_option_id: '13', user_id: '1')
Vote.create(poll_option_id: '13', user_id: '2')
Vote.create(poll_option_id: '13', user_id: '3')
Vote.create(poll_option_id: '13', user_id: '4')
Vote.create(poll_option_id: '14', user_id: '5')
Vote.create(poll_option_id: '14', user_id: '6')
Vote.create(poll_option_id: '14', user_id: '7')
Vote.create(poll_option_id: '14', user_id: '8')

Vote.create(poll_option_id: '15', user_id: '9')
Vote.create(poll_option_id: '16', user_id: '10')

Vote.create(poll_option_id: '17', user_id: '1')
Vote.create(poll_option_id: '17', user_id: '2')
Vote.create(poll_option_id: '17', user_id: '3')
Vote.create(poll_option_id: '18', user_id: '4')
Vote.create(poll_option_id: '18', user_id: '5')
Vote.create(poll_option_id: '18', user_id: '6')
Vote.create(poll_option_id: '18', user_id: '7')
Vote.create(poll_option_id: '18', user_id: '8')
Vote.create(poll_option_id: '18', user_id: '9')
Vote.create(poll_option_id: '18', user_id: '10')

Vote.create(poll_option_id: '19', user_id: '2')
Vote.create(poll_option_id: '20', user_id: '3')
Vote.create(poll_option_id: '20', user_id: '4')
Vote.create(poll_option_id: '20', user_id: '5')
Vote.create(poll_option_id: '20', user_id: '6')
Vote.create(poll_option_id: '20', user_id: '7')
Vote.create(poll_option_id: '20', user_id: '8')

Vote.create(poll_option_id: '21', user_id: '9')
Vote.create(poll_option_id: '21', user_id: '10')
Vote.create(poll_option_id: '21', user_id: '1')
Vote.create(poll_option_id: '22', user_id: '2')
Vote.create(poll_option_id: '22', user_id: '3')
Vote.create(poll_option_id: '22', user_id: '4')
Vote.create(poll_option_id: '22', user_id: '5')

Vote.create(poll_option_id: '23', user_id: '6')
Vote.create(poll_option_id: '23', user_id: '7')
Vote.create(poll_option_id: '24', user_id: '8')
Vote.create(poll_option_id: '24', user_id: '9')

Vote.create(poll_option_id: '25', user_id: '10')
Vote.create(poll_option_id: '26', user_id: '1')
Vote.create(poll_option_id: '26', user_id: '2')
Vote.create(poll_option_id: '26', user_id: '3')

Vote.create(poll_option_id: '27', user_id: '4')
Vote.create(poll_option_id: '28', user_id: '5')

Vote.create(poll_option_id: '29', user_id: '6')
Vote.create(poll_option_id: '29', user_id: '7')
Vote.create(poll_option_id: '29', user_id: '8')
Vote.create(poll_option_id: '30', user_id: '9')

Vote.create(poll_option_id: '31', user_id: '10')
Vote.create(poll_option_id: '31', user_id: '1')
Vote.create(poll_option_id: '32', user_id: '2')
Vote.create(poll_option_id: '32', user_id: '3')

Vote.create(poll_option_id: '33', user_id: '4')
Vote.create(poll_option_id: '33', user_id: '5')
Vote.create(poll_option_id: '34', user_id: '6')
Vote.create(poll_option_id: '34', user_id: '7')
Vote.create(poll_option_id: '34', user_id: '8')

Vote.create(poll_option_id: '35', user_id: '9')
Vote.create(poll_option_id: '35', user_id: '10')
Vote.create(poll_option_id: '36', user_id: '1')

Vote.create(poll_option_id: '37', user_id: '2')
Vote.create(poll_option_id: '37', user_id: '3')
Vote.create(poll_option_id: '37', user_id: '4')
Vote.create(poll_option_id: '37', user_id: '5')
Vote.create(poll_option_id: '37', user_id: '6')
Vote.create(poll_option_id: '37', user_id: '7')
Vote.create(poll_option_id: '37', user_id: '8')
Vote.create(poll_option_id: '37', user_id: '9')
Vote.create(poll_option_id: '37', user_id: '10')
Vote.create(poll_option_id: '38', user_id: '1')



Vote.create(poll_option_id: '39', user_id: '2')
Vote.create(poll_option_id: '39', user_id: '3')
Vote.create(poll_option_id: '40', user_id: '4')

Vote.create(poll_option_id: '41', user_id: '5')
Vote.create(poll_option_id: '41', user_id: '6')
Vote.create(poll_option_id: '42', user_id: '7')
Vote.create(poll_option_id: '42', user_id: '8')
Vote.create(poll_option_id: '42', user_id: '9')
Vote.create(poll_option_id: '42', user_id: '10')
Vote.create(poll_option_id: '42', user_id: '1')
Vote.create(poll_option_id: '42', user_id: '2')
Vote.create(poll_option_id: '42', user_id: '3')
